services:
  auth-service:
    image: ttrungn/mts-auth-service:latest
    container_name: auth-service
    expose:
      - 8080
    env_file:
      - .env
    networks:
      - metro-net
  sample-service:
    image: ttrungn/mts-sample-service:latest
    container_name: sample-service
    expose:
      - 8080
    env_file:
      - .env
    networks:
      - metro-net
  api-gateway:
    build:
      context: .
      dockerfile: ./YarpApiGateway/Dockerfile
    container_name: api-gateway
    ports:
      - "9000:8080"
    depends_on:
      - auth-service
      - sample-service
    env_file:
      - .env
    networks:
      - metro-net

networks:
  metro-net:
    driver: bridge