services:
  user-service:
    image: "${REGISTRY_USERNAME}/mts-user-service:${IMAGE_TAG-latest}"
    container_name: user-service
    volumes:
      - /etc/localtime:/etc/localtime:ro
    expose:
      - 8080
    env_file:
      - .env
    networks:
      - metro-net
  sample-service:
    image: "${REGISTRY_USERNAME}/mts-sample-service:${IMAGE_TAG-latest}"
    container_name: sample-service
    volumes:
      - /etc/localtime:/etc/localtime:ro
    expose:
      - 8080
    env_file:
      - .env
    networks:
      - metro-net
  catalog-service:
    image: "${REGISTRY_USERNAME}/mts-catalog-service:${IMAGE_TAG-latest}"
    container_name: catalog-service
    volumes:
      - /etc/localtime:/etc/localtime:ro
    expose:
      - 8080
    env_file:
      - .env
    networks:
      - metro-net
  order-service:
    image: "${REGISTRY_USERNAME}/mts-order-service:${IMAGE_TAG-latest}"
    container_name: order-service
    volumes:
      - /etc/localtime:/etc/localtime:ro
    expose:
      - 8080
    env_file:
      - .env
    networks:
      - metro-net
  notification-service:
    image: "${REGISTRY_USERNAME}/mts-notification-service:${IMAGE_TAG-latest}"
    container_name: notification-service
    volumes:
      - /etc/localtime:/etc/localtime:ro
    expose:
      - 8080
    env_file:
      - .env
    networks:
      - metro-net
  api-gateway:
    image: "${REGISTRY_USERNAME}/mts-yarp-api-gateway:${IMAGE_TAG-latest}"
    container_name: api-gateway
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "9000:8080"
    depends_on:
      - user-service
      - sample-service
    env_file:
      - .env
    networks:
      - metro-net

networks:
  metro-net:
    driver: bridge