name: CI – Build & Push Services

on:
  push:
    branches: [ trungn ]
    paths:
      - 'AuthService/**'

jobs:
  auth:
    if: ${{
      contains(join(github.event.commits.*.added, ' '), 'AuthService/')
      || contains(join(github.event.commits.*.modified, ' '), 'AuthService/')
      }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get SHA
        id: sha
        run: echo "::set-output name=sha::$(git rev-parse --short HEAD)"
      - uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          context: .
          file: ./AuthService/src/Web/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/mts-auth-service:${{ steps.sha.outputs.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/mts-auth-service:latest
