name: CI – Build & Push Services

on:
  push:
    branches: [ trung ]
    paths:
      - 'AuthService/**'

jobs:
  auth:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get SHA
        id: sha
        run: echo "::set-output name=sha::$(git rev-parse --short HEAD)"
      - uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          context: .
          file: ./AuthService/src/Web/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/mts-auth-service:${{ steps.sha.outputs.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/mts-auth-service:latest
          build-args: |
            WRITE_DB=${{ secrets.AUTH_SERVICE_WRITE_DB_CONNECTION }}
            READ_DB=POSTGRESQL_URL
            JWT_SECRET=${{ secrets.SHARED_JWT_SECRET }}
            JWT_ISSUER=${{ secrets.SHARED_JWT_ISSUER }}
            JWT_AUDIENCE=${{ secrets.SHARED_JWT_AUDIENCE }}
            JWT_LIFETIME_MINUTES=${{ secrets.SHARED_JWT_LIFETIME_MINUTES }}
