name: CI – Build & Push SampleService Docker Image Dev

on:
  push:
    branches: [ dev ]
    paths:
      - 'SampleService/**'

jobs:
  sample-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pull previous cache image
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/mts-sample-service-dev:cache || echo "no cache yet"

      - name: Restore buildx local cache
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: buildx-sample-${{ runner.os }}
          restore-keys: |
            buildx-sample-${{ runner.os }}

      - name: Prepare local cache dir
        run: mkdir -p /tmp/.buildx-cache

      - name: Set up QEMU for multi-arch
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker-container
          install: true

      - name: Get Git short SHA
        id: sha
        run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push SampleService (multi-arch)
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./SampleService/src/Web/Dockerfile
          platforms: linux/amd64, linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/mts-sample-service-dev:${{ steps.sha.outputs.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/mts-sample-service-dev:latest
          cache-from: |
            type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/mts-sample-service-dev:cache
            type=local,src=/tmp/.buildx-cache
          cache-to: |
            type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/mts-sample-service-dev:cache,mode=max
            type=local,dest=/tmp/.buildx-cache,mode=max
